/**
 * Code reference seed data — extracted from custos-intel-fire-code-kb.html
 * All fire code requirements for Chippewa Falls, WI jurisdiction
 */
export const codeReferencesSeed = [
  // =============================================================
  // SPRINKLER SPACING — NFPA 13 (2012)
  // =============================================================
  {
    category: 'sprinkler_spacing',
    codeSource: 'NFPA_13_2012',
    section: '§8.6.2.2.1',
    title: 'Max sprinkler spacing — Standard Pendent/Upright (Light Hazard)',
    content: 'Maximum spacing 15 ft between sprinklers. Minimum distance to wall 4 in. Maximum distance to wall 7 ft 6 in.',
    numericValue: 15,
    unit: 'ft',
    tags: ['sprinkler', 'spacing', 'light hazard', 'pendent', 'upright'],
    sortOrder: 1,
  },
  {
    category: 'sprinkler_spacing',
    codeSource: 'NFPA_13_2012',
    section: '§8.6.2.2.1',
    title: 'Max sprinkler spacing — Standard Pendent/Upright (Ordinary Hazard)',
    content: 'Maximum spacing 15 ft between sprinklers. Minimum distance to wall 4 in. Maximum distance to wall 7 ft 6 in.',
    numericValue: 15,
    unit: 'ft',
    tags: ['sprinkler', 'spacing', 'ordinary hazard', 'pendent', 'upright'],
    sortOrder: 2,
  },
  {
    category: 'sprinkler_spacing',
    codeSource: 'NFPA_13_2012',
    section: '§8.6.2.2.1',
    title: 'Max sprinkler spacing — Standard Pendent/Upright (Extra Hazard ≥0.25 gpm/ft²)',
    content: 'Maximum spacing 12 ft between sprinklers. Minimum distance to wall 4 in. Maximum distance to wall 6 ft.',
    numericValue: 12,
    unit: 'ft',
    tags: ['sprinkler', 'spacing', 'extra hazard', 'pendent', 'upright'],
    sortOrder: 3,
  },
  {
    category: 'sprinkler_spacing',
    codeSource: 'NFPA_13_2012',
    section: '§8.8',
    title: 'Max sprinkler spacing — Sidewall (Light Hazard)',
    content: 'Maximum spacing 14 ft between sidewall sprinklers. Minimum distance to wall 4 in. Maximum distance to wall 7 ft.',
    numericValue: 14,
    unit: 'ft',
    tags: ['sprinkler', 'spacing', 'sidewall', 'light hazard'],
    sortOrder: 4,
  },
  {
    category: 'sprinkler_spacing',
    codeSource: 'NFPA_13_2012',
    section: '§8.6.2',
    title: 'Extended Coverage Pendent spacing',
    content: 'Maximum spacing per listing. Minimum and maximum distances to wall per listing. Must be installed per manufacturer listing.',
    numericValue: null,
    unit: null,
    tags: ['sprinkler', 'spacing', 'extended coverage'],
    sortOrder: 5,
  },
  {
    category: 'sprinkler_spacing',
    codeSource: 'NFPA_13R',
    section: '§6.2',
    title: 'Residential sprinkler spacing (NFPA 13R)',
    content: 'Maximum spacing per listing. Minimum distance to wall 4 in. Maximum distance to wall per listing.',
    numericValue: null,
    unit: null,
    tags: ['sprinkler', 'spacing', 'residential', '13R'],
    sortOrder: 6,
  },
  {
    category: 'sprinkler_spacing',
    codeSource: 'NFPA_13_2012',
    section: '§8.6.2.2.3',
    title: 'Minimum sprinkler to wall distance',
    content: 'Sprinklers shall be located a minimum of 4 inches from any wall.',
    numericValue: 4,
    unit: 'in',
    tags: ['sprinkler', 'wall distance', 'minimum'],
    sortOrder: 7,
  },

  // =============================================================
  // SPRINKLER COVERAGE AREA PER HEAD
  // =============================================================
  {
    category: 'sprinkler_coverage',
    codeSource: 'NFPA_13_2012',
    section: '§8.6.2.2.1',
    title: 'Max coverage area — Unobstructed Non-combustible, Light Hazard',
    content: 'Maximum protection area per sprinkler: 225 ft². Applies to unobstructed, non-combustible construction with Light Hazard occupancy.',
    numericValue: 225,
    unit: 'ft²',
    tags: ['sprinkler', 'coverage', 'light hazard', 'unobstructed'],
    sortOrder: 10,
  },
  {
    category: 'sprinkler_coverage',
    codeSource: 'NFPA_13_2012',
    section: '§8.6.2.2.1',
    title: 'Max coverage area — Unobstructed Non-combustible, Ordinary Hazard',
    content: 'Maximum protection area per sprinkler: 130 ft². Applies to unobstructed, non-combustible construction with Ordinary Hazard occupancy.',
    numericValue: 130,
    unit: 'ft²',
    tags: ['sprinkler', 'coverage', 'ordinary hazard', 'unobstructed'],
    sortOrder: 11,
  },
  {
    category: 'sprinkler_coverage',
    codeSource: 'NFPA_13_2012',
    section: '§8.6.2.2.1',
    title: 'Max coverage area — Obstructed Combustible, Light Hazard',
    content: 'Maximum protection area per sprinkler: 168 ft². Applies to obstructed, combustible construction with Light Hazard occupancy.',
    numericValue: 168,
    unit: 'ft²',
    tags: ['sprinkler', 'coverage', 'light hazard', 'obstructed', 'combustible'],
    sortOrder: 12,
  },
  {
    category: 'sprinkler_coverage',
    codeSource: 'NFPA_13_2012',
    section: '§8.6.2.2.1',
    title: 'Max coverage area — Obstructed Combustible, Ordinary Hazard',
    content: 'Maximum protection area per sprinkler: 130 ft². Applies to obstructed, combustible construction with Ordinary Hazard occupancy.',
    numericValue: 130,
    unit: 'ft²',
    tags: ['sprinkler', 'coverage', 'ordinary hazard', 'obstructed', 'combustible'],
    sortOrder: 13,
  },
  {
    category: 'sprinkler_coverage',
    codeSource: 'NFPA_13_2012',
    section: '§8.6.2.2.1',
    title: 'Max coverage area — Any construction, Extra Hazard',
    content: 'Maximum protection area per sprinkler: 100 ft². Applies to all construction types with Extra Hazard occupancy.',
    numericValue: 100,
    unit: 'ft²',
    tags: ['sprinkler', 'coverage', 'extra hazard'],
    sortOrder: 14,
  },

  // =============================================================
  // DEFLECTOR DISTANCES
  // =============================================================
  {
    category: 'sprinkler_deflector',
    codeSource: 'NFPA_13_2012',
    section: '§8.6.4.1',
    title: 'Deflector distance — Standard Pendent (unobstructed smooth ceiling)',
    content: 'Minimum distance from deflector to ceiling: 1 in. Maximum distance: 12 in.',
    numericValue: 12,
    unit: 'in',
    tags: ['sprinkler', 'deflector', 'ceiling distance', 'pendent'],
    sortOrder: 20,
  },
  {
    category: 'sprinkler_deflector',
    codeSource: 'NFPA_13_2012',
    section: '§8.6.4.1',
    title: 'Deflector distance — Standard Upright (unobstructed)',
    content: 'Minimum distance from deflector to ceiling: 1 in. Maximum distance: 12 in.',
    numericValue: 12,
    unit: 'in',
    tags: ['sprinkler', 'deflector', 'ceiling distance', 'upright'],
    sortOrder: 21,
  },
  {
    category: 'sprinkler_deflector',
    codeSource: 'NFPA_13_2012',
    section: '§8.8',
    title: 'Deflector distance — Sidewall',
    content: 'Minimum distance from deflector to ceiling: 4 in. Maximum distance: 6 in.',
    numericValue: 6,
    unit: 'in',
    tags: ['sprinkler', 'deflector', 'ceiling distance', 'sidewall'],
    sortOrder: 22,
  },
  {
    category: 'sprinkler_deflector',
    codeSource: 'NFPA_13_2012',
    section: '§8.6.4',
    title: 'Deflector distance — Concealed/Recessed',
    content: 'Install per listing. Distance determined by manufacturer specifications.',
    numericValue: null,
    unit: null,
    tags: ['sprinkler', 'deflector', 'concealed', 'recessed'],
    sortOrder: 23,
  },

  // =============================================================
  // SPRINKLER DENSITY / DESIGN AREA
  // =============================================================
  {
    category: 'sprinkler_density',
    codeSource: 'NFPA_13_2012',
    section: 'Fig. 11.2.3.1.1',
    title: 'Design density — Light Hazard',
    content: 'Minimum design density 0.10 gpm/ft² over 1,500 ft² design area. Maximum sprinkler spacing 15 ft.',
    numericValue: 0.10,
    unit: 'gpm/ft²',
    tags: ['density', 'design area', 'light hazard', 'hydraulic'],
    sortOrder: 30,
  },
  {
    category: 'sprinkler_density',
    codeSource: 'NFPA_13_2012',
    section: 'Fig. 11.2.3.1.1',
    title: 'Design density — Ordinary Hazard Group 1',
    content: 'Minimum design density 0.15 gpm/ft² over 1,500 ft² design area. Maximum sprinkler spacing 15 ft.',
    numericValue: 0.15,
    unit: 'gpm/ft²',
    tags: ['density', 'design area', 'ordinary hazard', 'OH1', 'hydraulic'],
    sortOrder: 31,
  },
  {
    category: 'sprinkler_density',
    codeSource: 'NFPA_13_2012',
    section: 'Fig. 11.2.3.1.1',
    title: 'Design density — Ordinary Hazard Group 2',
    content: 'Minimum design density 0.20 gpm/ft² over 1,500 ft² design area. Maximum sprinkler spacing 15 ft.',
    numericValue: 0.20,
    unit: 'gpm/ft²',
    tags: ['density', 'design area', 'ordinary hazard', 'OH2', 'hydraulic'],
    sortOrder: 32,
  },
  {
    category: 'sprinkler_density',
    codeSource: 'NFPA_13_2012',
    section: 'Fig. 11.2.3.1.1',
    title: 'Design density — Extra Hazard Group 1',
    content: 'Minimum design density 0.30 gpm/ft² over 2,500 ft² design area. Maximum sprinkler spacing 12 ft.',
    numericValue: 0.30,
    unit: 'gpm/ft²',
    tags: ['density', 'design area', 'extra hazard', 'EH1', 'hydraulic'],
    sortOrder: 33,
  },
  {
    category: 'sprinkler_density',
    codeSource: 'NFPA_13_2012',
    section: 'Fig. 11.2.3.1.1',
    title: 'Design density — Extra Hazard Group 2',
    content: 'Minimum design density 0.40 gpm/ft² over 2,500 ft² design area. Maximum sprinkler spacing 12 ft.',
    numericValue: 0.40,
    unit: 'gpm/ft²',
    tags: ['density', 'design area', 'extra hazard', 'EH2', 'hydraulic'],
    sortOrder: 34,
  },
  {
    category: 'sprinkler_density',
    codeSource: 'NFPA_13_2012',
    section: '§8.6.2.2.2',
    title: 'Small Room Rule',
    content: 'In rooms ≤800 ft² (Light Hazard) or ≤400 ft² (Ordinary Hazard), a single sprinkler may protect the entire room if the room dimensions do not exceed the maximum listed spacing of the sprinkler.',
    numericValue: 800,
    unit: 'ft²',
    tags: ['sprinkler', 'small room', 'single head', 'light hazard', 'ordinary hazard'],
    sortOrder: 35,
  },

  // =============================================================
  // FIRE ACCESS — IFC 2012
  // =============================================================
  {
    category: 'fire_access',
    codeSource: 'IFC_2012',
    section: '§503.2.1',
    title: 'Minimum fire apparatus access road width',
    content: 'Fire apparatus access roads shall have an unobstructed width of not less than 20 ft with an all-weather driving surface.',
    numericValue: 20,
    unit: 'ft',
    tags: ['fire access', 'road width', 'apparatus', 'minimum'],
    sortOrder: 40,
  },
  {
    category: 'fire_access',
    codeSource: 'IFC_2012',
    section: '§503.2.1',
    title: 'Minimum vertical clearance',
    content: 'Fire apparatus access roads shall have a minimum vertical clearance of 13 ft 6 in above the road surface.',
    numericValue: 13.5,
    unit: 'ft',
    tags: ['fire access', 'vertical clearance', 'height'],
    sortOrder: 41,
  },
  {
    category: 'fire_access',
    codeSource: 'IFC_2012',
    section: '§503.2.4',
    title: 'Minimum turning radius (inside)',
    content: 'Inside turning radius minimum 25 ft per local fire code official.',
    numericValue: 25,
    unit: 'ft',
    tags: ['fire access', 'turning radius', 'inside'],
    sortOrder: 42,
  },
  {
    category: 'fire_access',
    codeSource: 'IFC_2012',
    section: '§503.2.4',
    title: 'Minimum turning radius (outside)',
    content: 'Outside turning radius minimum 50 ft per local fire code official.',
    numericValue: 50,
    unit: 'ft',
    tags: ['fire access', 'turning radius', 'outside'],
    sortOrder: 43,
  },
  {
    category: 'fire_access',
    codeSource: 'IFC_2012',
    section: '§D103.4',
    title: 'Maximum dead-end road length',
    content: 'Dead-end fire apparatus access roads in excess of 150 ft in length shall be provided with an approved turnaround.',
    numericValue: 150,
    unit: 'ft',
    tags: ['fire access', 'dead end', 'turnaround', 'cul-de-sac'],
    sortOrder: 44,
  },
  {
    category: 'fire_access',
    codeSource: 'IFC_2012',
    section: '§503.3',
    title: 'Fire lane marking requirement',
    content: 'Fire apparatus access roads shall be marked with NO PARKING FIRE LANE signage where required by the fire code official.',
    numericValue: null,
    unit: null,
    tags: ['fire access', 'fire lane', 'no parking', 'signage'],
    sortOrder: 45,
  },
  {
    category: 'fire_access',
    codeSource: 'IFC_2012',
    section: '§503.2.7',
    title: 'Maximum road grade',
    content: 'The grade of fire apparatus access roads shall not exceed 10%. Steeper grades require fire official approval.',
    numericValue: 10,
    unit: '%',
    tags: ['fire access', 'grade', 'slope'],
    sortOrder: 46,
  },
  {
    category: 'fire_access',
    codeSource: 'IFC_2012',
    section: '§503.2.3',
    title: 'Minimum road load capacity',
    content: 'Fire apparatus access roads shall be designed and maintained to support the imposed loads of fire apparatus (minimum 75,000 lbs GVW).',
    numericValue: 75000,
    unit: 'lbs',
    tags: ['fire access', 'load capacity', 'weight', 'GVW'],
    sortOrder: 47,
  },
  {
    category: 'fire_access',
    codeSource: 'IFC_2012',
    section: '§D105',
    title: 'Aerial fire apparatus access',
    content: 'Buildings ≥3 stories or >30 ft in height require aerial fire apparatus access. Aerial access roads shall have a minimum unobstructed width of 26 ft and be positioned 15–30 ft from the building face.',
    numericValue: 26,
    unit: 'ft',
    tags: ['fire access', 'aerial', 'ladder', 'tall building'],
    sortOrder: 48,
  },

  // =============================================================
  // HYDRANT DISTANCE & SPACING — IFC 2012
  // =============================================================
  {
    category: 'hydrant_distance',
    codeSource: 'IFC_2012',
    section: '§507.5.1',
    title: 'Max hydrant distance from building (no sprinklers)',
    content: 'Fire hydrants shall be within 500 ft of all portions of the facility or building, measured as hose lay distance (not straight line). Applies to buildings without automatic sprinkler systems.',
    numericValue: 500,
    unit: 'ft',
    tags: ['hydrant', 'distance', 'no sprinklers', 'hose lay'],
    sortOrder: 50,
  },
  {
    category: 'hydrant_distance',
    codeSource: 'IFC_2012',
    section: '§507.5.1',
    title: 'Max hydrant distance from building (with sprinklers)',
    content: 'Fire hydrants shall be within 750 ft of all portions of the facility or building where an approved automatic sprinkler system is installed. Exception does not apply to Group H, I, high-rise, or high-piled storage.',
    numericValue: 750,
    unit: 'ft',
    tags: ['hydrant', 'distance', 'sprinklered', 'hose lay'],
    sortOrder: 51,
  },
  {
    category: 'hydrant_distance',
    codeSource: 'IFC_2012',
    section: '§507.5.1',
    title: 'Min hydrant distance from building',
    content: 'Fire hydrants shall be located a minimum of 40 ft from the face of the building (common requirement).',
    numericValue: 40,
    unit: 'ft',
    tags: ['hydrant', 'distance', 'minimum', 'building face'],
    sortOrder: 52,
  },
  {
    category: 'hydrant_distance',
    codeSource: 'IFC_2012',
    section: 'App. C',
    title: 'Hydrant spacing — Fire flow ≤1,750 gpm',
    content: 'Minimum 1 hydrant. Maximum spacing 500 ft. Average area per hydrant 160,000 ft².',
    numericValue: 500,
    unit: 'ft',
    tags: ['hydrant', 'spacing', 'fire flow', '1750 gpm'],
    sortOrder: 53,
  },
  {
    category: 'hydrant_distance',
    codeSource: 'IFC_2012',
    section: 'App. C',
    title: 'Hydrant spacing — Fire flow 2,000–2,250 gpm',
    content: 'Minimum 2 hydrants. Maximum spacing 450 ft. Average area per hydrant 140,000 ft².',
    numericValue: 450,
    unit: 'ft',
    tags: ['hydrant', 'spacing', 'fire flow', '2000 gpm'],
    sortOrder: 54,
  },
  {
    category: 'hydrant_distance',
    codeSource: 'IFC_2012',
    section: 'App. C',
    title: 'Hydrant spacing — Fire flow 2,500 gpm',
    content: 'Minimum 2 hydrants. Maximum spacing 450 ft. Average area per hydrant 130,000 ft².',
    numericValue: 450,
    unit: 'ft',
    tags: ['hydrant', 'spacing', 'fire flow', '2500 gpm'],
    sortOrder: 55,
  },
  {
    category: 'hydrant_distance',
    codeSource: 'IFC_2012',
    section: 'App. C',
    title: 'Hydrant spacing — Fire flow 3,000–3,500 gpm',
    content: 'Minimum 3 hydrants. Maximum spacing 400 ft. Average area per hydrant 110,000 ft².',
    numericValue: 400,
    unit: 'ft',
    tags: ['hydrant', 'spacing', 'fire flow', '3000 gpm'],
    sortOrder: 56,
  },
  {
    category: 'hydrant_distance',
    codeSource: 'IFC_2012',
    section: 'App. C',
    title: 'Hydrant spacing — Fire flow 4,000–4,500 gpm',
    content: 'Minimum 3 hydrants. Maximum spacing 350 ft. Average area per hydrant 100,000 ft².',
    numericValue: 350,
    unit: 'ft',
    tags: ['hydrant', 'spacing', 'fire flow', '4000 gpm'],
    sortOrder: 57,
  },
  {
    category: 'hydrant_distance',
    codeSource: 'IFC_2012',
    section: 'App. C',
    title: 'Hydrant spacing — Fire flow 5,000–5,500 gpm',
    content: 'Minimum 4 hydrants. Maximum spacing 300 ft. Average area per hydrant 90,000 ft².',
    numericValue: 300,
    unit: 'ft',
    tags: ['hydrant', 'spacing', 'fire flow', '5000 gpm'],
    sortOrder: 58,
  },
  {
    category: 'hydrant_distance',
    codeSource: 'IFC_2012',
    section: 'App. C',
    title: 'Hydrant spacing — Fire flow ≥6,000 gpm',
    content: 'Minimum 5+ hydrants. Maximum spacing 250 ft. Average area per hydrant 80,000 ft².',
    numericValue: 250,
    unit: 'ft',
    tags: ['hydrant', 'spacing', 'fire flow', '6000 gpm'],
    sortOrder: 59,
  },

  // =============================================================
  // FDC REQUIREMENTS — NFPA 14 (2010) / IFC 2012
  // =============================================================
  {
    category: 'fdc_requirements',
    codeSource: 'NFPA_14_2010',
    section: '§7.12',
    title: 'FDC max distance from nearest hydrant',
    content: 'Fire department connections shall be located not more than 100 ft from the nearest fire hydrant, measured by an approved route.',
    numericValue: 100,
    unit: 'ft',
    tags: ['FDC', 'hydrant distance', 'maximum'],
    sortOrder: 60,
  },
  {
    category: 'fdc_requirements',
    codeSource: 'NFPA_14_2010',
    section: '§7.12',
    title: 'FDC min separation from hydrant',
    content: 'Fire department connections shall be separated from the face of the fire hydrant by a minimum of 6 ft.',
    numericValue: 6,
    unit: 'ft',
    tags: ['FDC', 'hydrant distance', 'minimum', 'separation'],
    sortOrder: 61,
  },
  {
    category: 'fdc_requirements',
    codeSource: 'IFC_2012',
    section: '§912.2',
    title: 'FDC visibility requirement',
    content: 'Fire department connections shall be visible from the street or nearest fire apparatus access road, or shall be indicated by an approved sign.',
    numericValue: null,
    unit: null,
    tags: ['FDC', 'visibility', 'street', 'signage'],
    sortOrder: 62,
  },
  {
    category: 'fdc_requirements',
    codeSource: 'NFPA_14_2010',
    section: '§7.12',
    title: 'FDC inlet size and count',
    content: 'FDC inlets shall be 2½ in NH (National Hose) thread. Provide one inlet per 250 gpm of system demand.',
    numericValue: 2.5,
    unit: 'in',
    tags: ['FDC', 'inlet', 'size', 'count', 'NH thread'],
    sortOrder: 63,
  },
  {
    category: 'fdc_requirements',
    codeSource: 'NFPA_14_2010',
    section: '§7.12',
    title: 'FDC inlet height above grade',
    content: 'FDC inlets shall be located between 18 in and 48 in above grade, measured to the center of the inlet.',
    numericValue: 18,
    unit: 'in',
    tags: ['FDC', 'height', 'grade', 'inlet'],
    sortOrder: 64,
  },
  {
    category: 'fdc_requirements',
    codeSource: 'NFPA_14_2010',
    section: '§7.12',
    title: 'FDC clapper/check valve',
    content: 'Each FDC inlet shall be equipped with an integral clapper (check valve) to prevent backflow.',
    numericValue: null,
    unit: null,
    tags: ['FDC', 'check valve', 'clapper', 'backflow'],
    sortOrder: 65,
  },
  {
    category: 'fdc_requirements',
    codeSource: 'NFPA_14_2010',
    section: '§7.12',
    title: 'FDC plugs or caps',
    content: 'FDC inlets shall be equipped with plugs or caps secured with chains.',
    numericValue: null,
    unit: null,
    tags: ['FDC', 'plugs', 'caps', 'chains'],
    sortOrder: 66,
  },
  {
    category: 'fdc_requirements',
    codeSource: 'IFC_2012',
    section: '§912.2.1',
    title: 'FDC obstruction clearance',
    content: 'No fences, posts, landscaping, or other obstructions shall block hose connection access to the FDC.',
    numericValue: null,
    unit: null,
    tags: ['FDC', 'clearance', 'obstruction', 'access'],
    sortOrder: 67,
  },

  // =============================================================
  // FDC SIGNAGE
  // =============================================================
  {
    category: 'fdc_signage',
    codeSource: 'NFPA_14_2010',
    section: '§6.4.6',
    title: 'FDC signage — minimum letter height',
    content: 'FDC signs shall have letters not less than 1 inch in height.',
    numericValue: 1,
    unit: 'in',
    tags: ['FDC', 'signage', 'letter height'],
    sortOrder: 70,
  },
  {
    category: 'fdc_signage',
    codeSource: 'NFPA_14_2010',
    section: '§6.4.6',
    title: 'FDC signage — system type identification',
    content: 'FDC signage shall indicate the system type: AUTOSPKR, STANDPIPE, or combined system (STANDPIPE AND AUTOSPKR).',
    numericValue: null,
    unit: null,
    tags: ['FDC', 'signage', 'system type', 'auto sprinkler', 'standpipe'],
    sortOrder: 71,
  },
  {
    category: 'fdc_signage',
    codeSource: 'NFPA_14_2010',
    section: '§6.4.6',
    title: 'FDC signage — pressure indication',
    content: 'Where system operating pressure exceeds 150 psi, a sign indicating the required pressure shall be displayed at the FDC.',
    numericValue: 150,
    unit: 'psi',
    tags: ['FDC', 'signage', 'pressure', 'high pressure'],
    sortOrder: 72,
  },

  // =============================================================
  // STANDPIPE REQUIREMENTS — IBC 2012
  // =============================================================
  {
    category: 'standpipe',
    codeSource: 'IBC_2012',
    section: '§905.3',
    title: 'Class I Standpipe — when required',
    content: 'Required in buildings where floor level of highest story is >30 ft above lowest fire dept access, or lowest story is >30 ft below highest fire dept access. Also required in covered mall buildings >2 stories, stages ≥1,000 ft², underground buildings, and heliports. Outlet: 2½ in valve at each floor landing in required stairways.',
    numericValue: 30,
    unit: 'ft',
    tags: ['standpipe', 'class I', 'height', 'stairway'],
    sortOrder: 80,
  },
  {
    category: 'standpipe',
    codeSource: 'IBC_2012',
    section: '§905.5',
    title: 'Class II Standpipe — when required',
    content: 'Class II standpipes with 1½ in hose connections required in covered mall buildings, stages ≥1,000 ft², and underground buildings. May be waived where building is fully sprinklered per NFPA 13.',
    numericValue: null,
    unit: null,
    tags: ['standpipe', 'class II', 'hose connection', 'mall'],
    sortOrder: 81,
  },
  {
    category: 'standpipe',
    codeSource: 'IBC_2012',
    section: '§905.3.1',
    title: 'Class III Standpipe — when required',
    content: 'Class III standpipes serve both fire department and occupant use. Required where Class I is required and building occupant use is desired. Outlets provide both 2½ in and 1½ in connections.',
    numericValue: null,
    unit: null,
    tags: ['standpipe', 'class III', 'combined', 'occupant use'],
    sortOrder: 82,
  },

  // =============================================================
  // FIRE RESISTANCE RATINGS — IBC 2012 Table 601
  // =============================================================
  {
    category: 'fire_resistance',
    codeSource: 'IBC_2012',
    section: 'Table 601',
    title: 'Type I-A fire-resistance ratings',
    content: 'Structural frame: 3 hr. Bearing walls (ext): 3 hr. Bearing walls (int): 3 hr. Floor: 2 hr. Roof: 1½ hr.',
    numericValue: 3,
    unit: 'hr',
    tags: ['construction type', 'I-A', 'fire resistance', 'rating'],
    sortOrder: 90,
  },
  {
    category: 'fire_resistance',
    codeSource: 'IBC_2012',
    section: 'Table 601',
    title: 'Type I-B fire-resistance ratings',
    content: 'Structural frame: 2 hr. Bearing walls (ext): 2 hr. Bearing walls (int): 2 hr. Floor: 2 hr. Roof: 1 hr.',
    numericValue: 2,
    unit: 'hr',
    tags: ['construction type', 'I-B', 'fire resistance', 'rating'],
    sortOrder: 91,
  },
  {
    category: 'fire_resistance',
    codeSource: 'IBC_2012',
    section: 'Table 601',
    title: 'Type II-A fire-resistance ratings',
    content: 'Structural frame: 1 hr. Bearing walls (ext): 1 hr. Bearing walls (int): 1 hr. Floor: 1 hr. Roof: 1 hr.',
    numericValue: 1,
    unit: 'hr',
    tags: ['construction type', 'II-A', 'fire resistance', 'rating'],
    sortOrder: 92,
  },
  {
    category: 'fire_resistance',
    codeSource: 'IBC_2012',
    section: 'Table 601',
    title: 'Type II-B fire-resistance ratings',
    content: 'Structural frame: 0 hr. Bearing walls (ext): 0 hr. Bearing walls (int): 0 hr. Floor: 0 hr. Roof: 0 hr. No fire-resistance requirements.',
    numericValue: 0,
    unit: 'hr',
    tags: ['construction type', 'II-B', 'fire resistance', 'rating', 'unprotected'],
    sortOrder: 93,
  },
  {
    category: 'fire_resistance',
    codeSource: 'IBC_2012',
    section: 'Table 601',
    title: 'Type III-A fire-resistance ratings',
    content: 'Structural frame: 1 hr. Bearing walls (ext): 2 hr. Bearing walls (int): 1 hr. Floor: 1 hr. Roof: 1 hr.',
    numericValue: 1,
    unit: 'hr',
    tags: ['construction type', 'III-A', 'fire resistance', 'rating'],
    sortOrder: 94,
  },
  {
    category: 'fire_resistance',
    codeSource: 'IBC_2012',
    section: 'Table 601',
    title: 'Type III-B fire-resistance ratings',
    content: 'Structural frame: 0 hr. Bearing walls (ext): 2 hr. Bearing walls (int): 0 hr. Floor: 0 hr. Roof: 0 hr.',
    numericValue: 0,
    unit: 'hr',
    tags: ['construction type', 'III-B', 'fire resistance', 'rating'],
    sortOrder: 95,
  },
  {
    category: 'fire_resistance',
    codeSource: 'IBC_2012',
    section: 'Table 601',
    title: 'Type V-A fire-resistance ratings',
    content: 'Structural frame: 1 hr. Bearing walls (ext): 1 hr. Bearing walls (int): 1 hr. Floor: 1 hr. Roof: 1 hr.',
    numericValue: 1,
    unit: 'hr',
    tags: ['construction type', 'V-A', 'fire resistance', 'rating'],
    sortOrder: 96,
  },
  {
    category: 'fire_resistance',
    codeSource: 'IBC_2012',
    section: 'Table 601',
    title: 'Type V-B fire-resistance ratings',
    content: 'Structural frame: 0 hr. Bearing walls (ext): 0 hr. Bearing walls (int): 0 hr. Floor: 0 hr. Roof: 0 hr. No fire-resistance requirements.',
    numericValue: 0,
    unit: 'hr',
    tags: ['construction type', 'V-B', 'fire resistance', 'rating', 'unprotected'],
    sortOrder: 97,
  },

  // =============================================================
  // FIRE ALARM — IBC 2012 / NFPA 72
  // =============================================================
  {
    category: 'fire_life_safety',
    codeSource: 'IBC_2012',
    section: '§907.2',
    title: 'Manual fire alarm — when required',
    content: 'Manual fire alarm required in: Group A (assembly) ≥300 occupant load; Group B (business) ≥500 occupant load (ambulatory care ≥100); Group E (educational); Group F (factory) ≥500; Group H (high hazard); Group I (institutional); Group M (mercantile) ≥500; Group R-1 (hotels/motels); Group R-2 (apartments) ≥17 units. Exception: Not required in Group B where fully sprinklered with occupant notification per §907.5.',
    numericValue: null,
    unit: null,
    tags: ['fire alarm', 'manual', 'pull station', 'occupancy', 'when required'],
    sortOrder: 100,
  },
  {
    category: 'fire_life_safety',
    codeSource: 'IBC_2012',
    section: '§907.2.9',
    title: 'Smoke detection — Group R requirements',
    content: 'Smoke alarms required in sleeping rooms and outside each sleeping area on each story of Group R occupancies.',
    numericValue: null,
    unit: null,
    tags: ['smoke detector', 'smoke alarm', 'sleeping room', 'residential', 'group R'],
    sortOrder: 101,
  },
  {
    category: 'fire_life_safety',
    codeSource: 'IBC_2012',
    section: '§907.2.6',
    title: 'Smoke detection — Group I requirements',
    content: 'Smoke detection required in corridors, waiting areas, and habitable rooms in Group I-1 occupancies.',
    numericValue: null,
    unit: null,
    tags: ['smoke detector', 'institutional', 'group I', 'corridor'],
    sortOrder: 102,
  },

  // =============================================================
  // MEANS OF EGRESS — IBC 2012
  // =============================================================
  {
    category: 'fire_life_safety',
    codeSource: 'IBC_2012',
    section: '§1005',
    title: 'Minimum egress width calculations',
    content: 'Stairways: 0.3 in per occupant. Other egress components: 0.2 in per occupant. Minimum corridor width: 44 in (36 in for ≤50 occupant load).',
    numericValue: 44,
    unit: 'in',
    tags: ['egress', 'width', 'corridor', 'stairway', 'occupant load'],
    sortOrder: 103,
  },
  {
    category: 'fire_life_safety',
    codeSource: 'IBC_2012',
    section: '§1016',
    title: 'Max exit access travel distance — Group R',
    content: 'Group R sprinklered: 250 ft. Group R unsprinklered: 200 ft.',
    numericValue: 250,
    unit: 'ft',
    tags: ['egress', 'travel distance', 'exit', 'residential', 'group R'],
    sortOrder: 104,
  },
  {
    category: 'fire_life_safety',
    codeSource: 'IBC_2012',
    section: '§1016',
    title: 'Max exit access travel distance — Group B',
    content: 'Group B sprinklered: 300 ft. Group B unsprinklered: 200 ft.',
    numericValue: 300,
    unit: 'ft',
    tags: ['egress', 'travel distance', 'exit', 'business', 'group B'],
    sortOrder: 105,
  },
  {
    category: 'fire_life_safety',
    codeSource: 'IBC_2012',
    section: '§1018.4',
    title: 'Maximum dead-end corridor length',
    content: 'Dead-end corridors shall not exceed 50 ft in length in sprinklered buildings, or 20 ft in unsprinklered buildings.',
    numericValue: 50,
    unit: 'ft',
    tags: ['egress', 'dead end', 'corridor', 'sprinklered'],
    sortOrder: 106,
  },
  {
    category: 'fire_life_safety',
    codeSource: 'IBC_2012',
    section: '§1021',
    title: 'Number of exits required',
    content: 'Two exits required when occupant load exceeds 10 (above or below grade) or per table thresholds.',
    numericValue: 10,
    unit: 'occupants',
    tags: ['egress', 'exits', 'number', 'occupant load', 'two exits'],
    sortOrder: 107,
  },

  // =============================================================
  // FIRE SEPARATION — IBC 2012
  // =============================================================
  {
    category: 'fire_life_safety',
    codeSource: 'IBC_2012',
    section: '§706',
    title: 'Fire walls — Group R occupancies',
    content: 'Group R occupancies: 2-hr fire wall required (or 3-hr for Type I construction).',
    numericValue: 2,
    unit: 'hr',
    tags: ['fire wall', 'separation', 'residential', 'group R', 'rating'],
    sortOrder: 110,
  },
  {
    category: 'fire_life_safety',
    codeSource: 'IBC_2012',
    section: '§708',
    title: 'Fire partitions — dwelling/sleeping unit separation',
    content: 'Dwelling/sleeping unit separation: 1-hr fire partition. Exception: ½-hr if sprinklered per §708.3. Corridor walls: 1-hr (0.5-hr for Groups B, E, U sprinklered).',
    numericValue: 1,
    unit: 'hr',
    tags: ['fire partition', 'dwelling', 'sleeping unit', 'corridor', 'separation'],
    sortOrder: 111,
  },
  {
    category: 'fire_life_safety',
    codeSource: 'IBC_2012',
    section: '§708.4',
    title: 'Shaft enclosure ratings',
    content: 'Shaft enclosures shall be rated 2-hr for buildings with 4 or more stories, 1-hr otherwise.',
    numericValue: 2,
    unit: 'hr',
    tags: ['shaft', 'enclosure', 'rating', 'elevator', 'stairway'],
    sortOrder: 112,
  },

  // =============================================================
  // WISCONSIN SPS 362 AMENDMENTS
  // =============================================================
  {
    category: 'wisconsin_amendments',
    codeSource: 'SPS_362',
    section: '§362.0903',
    title: 'WI Automatic Sprinkler Systems — Group R',
    content: 'Automatic sprinkler system per IBC §903.3 required throughout all buildings with a Group R fire area. Exceptions: ≤4 dwelling units AND ≤2 stories above grade AND not on community/municipal water system. Townhouses and qualifying multifamily may use NFPA 13D where permitted by SPS 362.0903(5). Key difference from base IBC: Wisconsin is more permissive on small multifamily not connected to public water.',
    numericValue: 4,
    unit: 'units',
    tags: ['wisconsin', 'sprinkler', 'group R', 'residential', 'NFPA 13D', 'exception'],
    sortOrder: 120,
  },
  {
    category: 'wisconsin_amendments',
    codeSource: 'SPS_362',
    section: '§362.0202',
    title: 'WI Mixed-Use Separation',
    content: 'Single-tenant R occupancy under Uniform Dwelling Code must be separated from commercial tenant by ≥1-hr rated fire partitions (IBC §708), ≥1-hr rated horizontal assemblies (IBC §711), or both. Wisconsin-specific amendment to IBC mixed-use separation tables.',
    numericValue: 1,
    unit: 'hr',
    tags: ['wisconsin', 'mixed use', 'separation', 'UDC', 'residential', 'commercial'],
    sortOrder: 121,
  },

  // =============================================================
  // CHIPPEWA FALLS LOCAL ORDINANCES
  // =============================================================
  {
    category: 'local_ordinances',
    codeSource: 'CHIPPEWA_FALLS',
    section: 'Ch. 14',
    title: 'Chippewa Falls — Building Code Adoption',
    content: 'Chippewa Falls adopts the Wisconsin Commercial Building Code (SPS 361-366) for all commercial and multifamily construction. Adopts NFPA 1 National Fire Protection Code for use, operation, and maintenance. All new commercial/multifamily construction, additions, or alterations require State Approved Plans prior to local building permit.',
    numericValue: null,
    unit: null,
    tags: ['chippewa falls', 'local code', 'adoption', 'state approved plans', 'NFPA 1'],
    sortOrder: 130,
  },
  {
    category: 'local_ordinances',
    codeSource: 'CHIPPEWA_FALLS',
    section: 'Ch. 14',
    title: 'Chippewa Falls — Grandfathered Ordinances',
    content: 'Per 2013 Act 270, Chippewa Falls may have grandfathered local fire code provisions that exceed state minimums. Verify with local fire marshal. Contact Inspection & Zoning: 715-726-2729.',
    numericValue: null,
    unit: null,
    tags: ['chippewa falls', 'grandfathered', 'local amendment', 'act 270', 'fire marshal'],
    sortOrder: 131,
  },
  {
    category: 'local_ordinances',
    codeSource: 'CHIPPEWA_FALLS',
    section: 'Ch. 17',
    title: 'Chippewa Falls — Zoning Impacts on Fire Access',
    content: 'Zoning setbacks may affect fire apparatus access and hydrant placement. Verify site plan dimensions against: front yard setbacks, side yard clearances (especially for aerial access on 3+ story buildings), lot coverage limits that may restrict fire lane placement. Required parking configurations must not block fire lane access or hydrant visibility/approach.',
    numericValue: null,
    unit: null,
    tags: ['chippewa falls', 'zoning', 'setback', 'fire access', 'parking', 'hydrant'],
    sortOrder: 132,
  },
];
